### ISSUE TITLE
weird IP returned by getent

### ISSUE THREAD

**Issue by lrkwz** [qoomon/docker-host#27] opened 2020-01-09 10:59 UTC
In my current network configuration happens that `getent ahostsv4 "host.docker.internal"` returns a list of public IP which by no mean are related to my environment.

![image](https://user-images.githubusercontent.com/1025560/72062175-87726500-32d7-11ea-8543-cf8444885368.png)

As a workaround I've forced DOCKER_HOST to the value returned by  `docker network inspect bridge --format='{{( index .IPAM.Config 0).Gateway}}'`.

**Comment by qoomon** [comment] 2020-01-09 21:51
Can you provide some details about your environment? (Version of OS and Docker)

**Comment by lrkwz** [comment] 2020-01-20 09:53
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

Docker version 19.03.3, build a872fc2f86

**Comment by qoomon** [comment] 2020-01-20 12:53
@lrkwz does it resolve to the same address all the time?

**Comment by qoomon** [comment] 2020-01-20 13:52
I can't reproduce your behaviour 
I tried the following setup:
* macOS Catalina 10.15.2
  * VirtualBox Ubuntu 19.10
    * Docker version 19.03.2
      * `sudo docker run --rm -it alpine getent ahostsv4 "host.docker.internal"`

and it return nothing as expected.
Do you have any ideas how to reproduce?
Is that behavior reproducible on another machine?

**Comment by lrkwz** [comment] 2020-01-21 09:39
1. Host with wired connection
2. docker-compose up; docker compose stop
3. Disconnect wire
4. Host with wifi connection (I don't remember if restart docker daemon)
3. docker-compose up

**Comment by qoomon** [comment] 2020-01-24 13:44
hmm I have no idea so far

**Comment by qoomon** [comment] 2020-01-28 19:51
@lrkwz do you have any idea what could go on there? for me it sound like a docker bug in general.
I don't think this behaviour is related to docker-host image/container, cause resolving the domain `host.docker.internal` is nothing I can influence.

**Closed** 2020-03-04 06:28 UTC
Labels: bug, help wanted
